:: PAGE ACCESS TOKEN 
set AMP_ACCESS_TOKEN=EAAIYrWZAihvEBAMtYwinSH6hM68njssJdDdSwUSMgSXZAPwHhKJgfXCC1XieW6XZB0YW4RRRw9rspjhMo7xXh5PCDAfIqJZBF5BgQWe7VvwsDyJS7z4ZBVeg59IAabG0JwhLWnZCo362k2Jc7NLD7p2f7gaC4ww24yPuzh2X5Asvf7lmp58hjAwBBqWkhVdlgZD
:: PAGE VERIF TOKEN
set AMP_VERIF_TOKEN=BrunoRakotomalala

:: DATABASE AUTHENTIFICATION
set ADAPTER=SQLITE
:: set ADAPTER=MYSQL
:: set ADAPTER=POSTGRESQL
:: set ADAPTER=MONGODB

::::: CASE MYSQL, POSTGRESQL OR MONGODB ADAPTER
set DB_HOST=
set DB_USER=
set DB_PASSWORD=
set DB_NAME=
:: set DB_PORT=
:: set SRV_PROTOCOL=1

:: CASE SQLITE ADAPTER
set DB_FILE=ampalibe.db


:: APPLICATION CONFIGURATION
set AMP_HOST=0.0.0.0
set AMP_PORT=4555

:: URL APPLICATION
set AMP_URL=


